/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.manna.batcher;

import org.junit.Test;
import org.manna.batcher.Batcher;
import org.manna.batcher.impl.DefaultBatcher;
import org.manna.batcher.impl.exceptions.MultipleInputException;
import org.manna.batcher.impl.exceptions.NotNumberInputException;
import org.manna.batcher.impl.exceptions.NullInputException;
import org.manna.batcher.impl.exceptions.OutOfRangeException;

public class Tests {
    @Test (expected = NullInputException.class)
    public void testNullOrEmpty() throws Exception {
      Batcher w= new DefaultBatcher();
      String[] testvalue = new String[0];
      w.batchrun(testvalue);       
    }
    @Test (expected = MultipleInputException.class)
    public void testMultipleInput() throws Exception {
      Batcher w= new DefaultBatcher();
      String[] testvalue = {"asd","sdfsd"};
      w.batchrun(testvalue);       
    }
    @Test (expected = NotNumberInputException.class)
    public void testNotNumberInput() throws Exception {
      Batcher w= new DefaultBatcher();
      String[] testvalue = {"asd"};
      w.batchrun(testvalue);       
    }
    @Test (expected = OutOfRangeException.class)
    public void testRangeOfNumberInput() throws Exception {
      Batcher w= new DefaultBatcher();
      String[] testvalue = {"230"};
      w.batchrun(testvalue);       
    }
    @Test
    public void testJob() throws Exception {
    	   Batcher w= new DefaultBatcher();
    	      String[] testvalue = {"2"};
    	      w.batchrun(testvalue);       
    	}
    
}
